feature/OS2UOL-85
os2ulf/os2udoglaer pull request #232
Opened 2024-06-21 11:06 UTC by nsj-novicell

Changed name on blocks according to how many columns it expected to be presented in

2024-06-21 11:19 UTC, SorenBonde requested changes
Some labels need to change

2024-06-21 11:19 UTC, SorenBonde commented on config/sync/block_content.type.code.yml
> +label: 'Kode (1)'
This can be used in all but depending on the script or iframe being inserted it might be best to limit it to 1 and 2 columns I think.

2024-06-21 11:19 UTC, SorenBonde commented on config/sync/block_content.type.appetizer.yml
> +label: 'Appetizer (1/2)'
I don't think we have any design for 2 column layouts so change this to 1 only.

2024-06-21 11:19 UTC, SorenBonde commented on config/sync/block_content.type.footer.yml
> +label: 'Footer (1)'
Change this to not include columns as this is not available in the layout builder and can only be added in content block section.

2024-06-21 11:19 UTC, SorenBonde commented on config/sync/block_content.type.hero.yml
> +label: 'Hero (1)'
This can be used in all columns.

2024-06-21 11:19 UTC, SorenBonde commented on config/sync/block_content.type.inline_navigation.yml
> +label: 'Inline Navigation (1/2/3)'
Change to only 1 column.

2024-06-21 11:19 UTC, SorenBonde commented on config/sync/block_content.type.spacer.yml
> +label: 'Spacer (1)'
Change to all columns.

2024-06-21 11:19 UTC, SorenBonde commented on config/sync/block_content.type.video.yml
> +label: 'Video (1/2/3)'
Change this to only 1.

2024-06-24 11:37 UTC, madsnorgaard approved these changes
All comments resolved - go merge!

2024-06-24 12:00 UTC, merged